### ISSUE TITLE
请问是否支持delete操作？

### ISSUE THREAD

**Issue by uchihayou** [liekkassmile/flink-connector-clickhouse-1.13#7]
用FlinkSql试了下从mysql同步到clickhouse，insert  update都可以，但delete似乎没有反应

**Comment by liekkassmile** [comment]
delete现在不支持，没开发
| |
lrh
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年07月19日 ***@***.***> 写道：

用FlinkSql试了下从mysql同步到clickhouse，insert update都可以，但delete似乎没有反应

**Comment by uchihayou** [comment]
好的，感谢！

**Comment by uchihayou** [comment]
好的，感谢！
